---
title: "Discussion of Analysis"
author:
- "Eli Pousson"
- "Erin Burman"
date: "4/5/2020"
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Evidence for disparate impact

This study found evidence of a disproportionate impact of basement sewage backups on majority-Black neighborhoods in Baltimore City. Substantially higher rates of backup requests in Black neighborhoods remained evident even after controlling for tracts’ median income, age, rent, and housing tenure. This finding support’s Ezell’s original analysis and indicates that the pattern has continued beyond her study period. We also found a strong positive effect of owner-occupancy on the rate of backup requests and a positive relationship between low-medium income versus low income and backup requests.

Identifying a discrete mechanism underlying racial disparities in backup events is challenging. Patterns of residential segregation and access to public services in Baltimore are shaped by a complex history of discrimination, redlining, public and private disinvestment, fiscal stress, and an aging built environment. Baltimore is a “shrinking city,” with a current population that is substantially smaller and less affluent than it was at its height in the 19th century. In shrinking cities, a declining tax base and aging infrastructure make compliance with increasingly strict environmental regulations challenging [@FaustWaterWastewaterInfrastructure2016].

This is a plausible framework for understanding the proliferation of, and limited response to, basement sewage backups in Baltimore, but it does not explain why Black neighborhoods appear worse affected than white neighborhoods after controlling for income. To understand this inequity, a more precise understanding of Baltimore’s history and environmental justice theory is necessary. Historic mortgage redlining of majority-Black neighborhoods prevented homeownership and intergenerational wealth building among Black residents, causing poverty in these communities. Prejudice and disinvestment further marginalized these neighborhoods and deprived them of public and private resources [@ZenouRacialDiscriminationRedlining2000].

Today, infrastructure improvement projects tend to privilege the neighborhoods and normative preferences of the white middle and upper classes [@FinewoodGreenInfrastructureHidden2019]. Thus, a number of interrelated phenomena influence the disproportionate impact of subpar water and sewer infrastructure on Black communities. 

Our results also indicate that basement sewage backups may occur most frequently to those who are least able to afford them. Most requests came from Census tracts with median incomes below the city and metropolitan means, and a $2,500 maximum on reimbursements potentially exposes residents to cleanup costs that are several times greater than their monthly housing expenses. 

### Limitations 

Our understanding of the disparate impacts of basement sewage backups is limited by what data is publicly available. We found evidence that the City of Baltimore’s public data about 311 request calls for basement sewage backups is sometimes unreliable or incomplete. For example, it appears that DPW often closes many open request tickets at once, suggesting that data on requests’ time-to-close reflects a bureaucratic process rather than the time that was necessary to address the caller’s problem. This variable is therefore unlikely to be useful. More broadly, it is likely that 311 data does not perfectly reflect the actual burden of basement sewage backups. Anecdotal evidence indicates that low-income residents and residents who fear retaliation are less likely to make 311 calls about basement backups they experience. In our analysis, we also found that the rate of 311 backup calls was much lower in tracts with a smaller percentage of residents owning homes. This could reflect a true reduction in rate in these neighborhoods, but this finding may instead reflect the reduced incentive for renters to report backups, because they are less likely to be financially responsible for cleanup. Unreliable data jeopardizes the City of Baltimore’s stated mission of data transparency and accountability. It also presents challenges for researchers and community members seeking to analyze the data and identify problems with DPW’s responses.

### Policy implications

Our project has several implications for future policy. Basement sewage backups disproportionately affect Black residents of Baltimore, as well as residents with low- and middle- incomes, so a policy remedy is clearly necessary. However, there are challenges in addressing disparities in access to public sanitation infrastructure. Legal scholars note that “there is no fundamental right to a basic level of drinking water and sanitation in the United States,” so access to services is instead dictated by a complicated variety of federal, state, and local policies. Additionally, proof of discriminatory intent is generally necessary to win anti-discrimination cases related to water and sewer infrastructure [@DavisLetJusticeRoll2015]. Within this complex legal and political landscape, community engagement, transparency, and accountability are all potential avenues to infrastructural equity [@QureshiBindingcivilcivic2018].

Recent legislation that made water more affordable for Baltimoreans arose from community organizing, grassroots activism, and political advocacy [@SwainWaterShutoffsOlder2020]; this victory can serve as an example for those interested in reducing disparities in basement sewage backups. The City of Baltimore can take similar action today and make the Expedited Reimbursement Program available to more residents with a larger payout.

### Directions for future work

Future research is necessary to understand the extent of the basement sewage backup crisis in Baltimore City. These studies may include analyses of DPW quarterly report data looking at attributed cause of backups, analyses of DPW quarterly report data on reimbursements, and analyses of effects of wastewater capital improvement projects.

Future research could also examine the role of spatial autocorrelation in the relationship between demographic factors and service request rates. It is currently unknown whether residual spatial dependence remains after our regression modeling of service requests.